---
- name: my test playbook
  hosts: all

  become: true

  tasks:

     - name: copy a file
       copy:
        src: /home/ansadmin/sai.html
        dest: /home/ansadmin
        mode: 0600
        owner: Rohit
