---
- name: handlers
  hosts: all
  become: true
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: installed
    notify: start httpd
  handlers:
  - name: start httpd
    service:
      name: httpd
      state: started
